FROM alpine:3.18 as downloads
RUN apk add --no-cache git wget \
    && git clone https://bitbucket.org/orserang/supermassa.git \
    && git clone https://github.com/guilherme-pereira/vcf2sm.git \
    && wget https://github.com/Cristianetaniguti/poly_containers/raw/master/poly_genocalls/subset.vcf \
    && wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py


FROM rocker/rstudio:4.0.3
COPY --from=downloads /supermassa/src/* /scripts/
COPY --from=downloads /vcf2sm/* /scripts/
COPY --from=downloads /subset.vcf /opt/
COPY --from=downloads /get-pip.py /
ENV PATH="/scripts:${PATH}"
ARG CRAN_REPO=https://packagemanager.rstudio.com/all/__linux__/focal/latest
ARG R_THREADS=4

RUN apt-get update && apt-get install --no-install-recommends -y \
        git \
        libfontconfig1-dev \
        libxml2-dev \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        zlib1g-dev \
        libbz2-dev \
        libcurl4-openssl-dev \
        python2 \
        python-tk \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && wget https://bootstrap.pypa.io/pip/2.7/get-pip.py -O get-pip.py \
        && python2 /get-pip.py && pip install \
        matplotlib==2.0.2 \
        numpy==1.16.6


# Install R packages
RUN install2.r --error -r ${CRAN_REPO} -n ${R_THREADS} \
        remotes \
        fitPoly \
        littler \
        BiocManager \
	qqman \
	devtools 

# installBioc.r and installGithub.r not working in docker hub

RUN R -e "BiocManager::install('pcaMethods');\
          BiocManager::install('BiocStyle');\
          BiocManager::install('VariantAnnotation')"

RUN R -e "devtools::install_github('lvclark/polyRAD')"